/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.ArrayList;

import javax.swing.JButton;

/**
 *
 * @author erick
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbContrasenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btAcceder = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        txtContrasenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        lbTitulo.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        lbTitulo.setText("Pagina de Inicio");

        lbUsuario.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbUsuario.setText("Usuario:");

        lbContrasenha.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        lbContrasenha.setText("Contraseña: ");

        btAcceder.setBackground(new java.awt.Color(204, 255, 204));
        btAcceder.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        btAcceder.setText("Acceder");

        btSalir.setBackground(new java.awt.Color(255, 153, 153));
        btSalir.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        btSalir.setText("Salir");

        btRegistrar.setBackground(new java.awt.Color(153, 255, 255));
        btRegistrar.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        btRegistrar.setText("Registrate");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(lbTitulo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbUsuario)
                                        .addGap(50, 50, 50)
                                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lbContrasenha)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContrasenha))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btAcceder)
                                .addGap(32, 32, 32)
                                .addComponent(btRegistrar)))
                        .addGap(0, 230, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalir)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbTitulo)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContrasenha)
                    .addComponent(txtContrasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcceder)
                    .addComponent(btRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<JButton> getButtons() {
      ArrayList<JButton> buttons = new ArrayList<>();
      buttons.add(btAcceder);
      buttons.add(btSalir);
      buttons.add(btRegistrar);
      return buttons;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcceder;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton btSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbContrasenha;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField txtContrasenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JButton getBtAcceder() {
      return btAcceder;
    }

    public void setBtAcceder(javax.swing.JButton btAcceder) {
      this.btAcceder = btAcceder;
    }

    public javax.swing.JButton getBtRegistrar() {
      return btRegistrar;
    }

    public void setBtRegistrar(javax.swing.JButton btRegistrar) {
      this.btRegistrar = btRegistrar;
    }

    public javax.swing.JButton getBtSalir() {
      return btSalir;
    }

    public void setBtSalir(javax.swing.JButton btSalir) {
      this.btSalir = btSalir;
    }

    public javax.swing.JPanel getjPanel1() {
      return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
      this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getjPanel2() {
      return jPanel2;
    }

    public void setjPanel2(javax.swing.JPanel jPanel2) {
      this.jPanel2 = jPanel2;
    }

    public javax.swing.JLabel getLbContrasenha() {
      return lbContrasenha;
    }

    public void setLbContrasenha(javax.swing.JLabel lbContrasenha) {
      this.lbContrasenha = lbContrasenha;
    }

    public javax.swing.JLabel getLbTitulo() {
      return lbTitulo;
    }

    public void setLbTitulo(javax.swing.JLabel lbTitulo) {
      this.lbTitulo = lbTitulo;
    }

    public javax.swing.JLabel getLbUsuario() {
      return lbUsuario;
    }

    public void setLbUsuario(javax.swing.JLabel lbUsuario) {
      this.lbUsuario = lbUsuario;
    }

    public javax.swing.JTextField getTxtUsuario() {
      return txtUsuario;
    }

    public void setTxtUsuario(javax.swing.JTextField txtUsuario) {
      this.txtUsuario = txtUsuario;
    }

    public javax.swing.JPasswordField getTxtContrasenha() {
      return txtContrasenha;
    }

    public void setTxtContrasenha(javax.swing.JPasswordField txtContrasenha) {
      this.txtContrasenha = txtContrasenha;
    }
}
